/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.student.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.student.ui.internal.StudentActivator;

public class StudentUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StudentActivator.getInstance().getInjector("org.xtext.example.student.Student");
	}

}
