/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.student.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.student.StudentRuntimeModule;
import org.xtext.example.student.StudentStandaloneSetup;
import org.xtext.example.student.ide.StudentIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class StudentIdeSetup extends StudentStandaloneSetup {
  @Override
  public Injector createInjector() {
    StudentRuntimeModule _studentRuntimeModule = new StudentRuntimeModule();
    StudentIdeModule _studentIdeModule = new StudentIdeModule();
    return Guice.createInjector(Modules2.mixin(_studentRuntimeModule, _studentIdeModule));
  }
}
