/*
 * generated by Xtext 2.11.0
 */
package org.wso2.vihanga.example.student


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class StudentRuntimeModule extends AbstractStudentRuntimeModule {
}
