/**
 * generated by Xtext 2.11.0
 */
package org.wso2.vihanga.example.student.ide;

import org.wso2.vihanga.example.student.ide.AbstractStudentIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class StudentIdeModule extends AbstractStudentIdeModule {
}
