/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.student.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class StudentProposalProvider extends AbstractStudentProposalProvider {
}
