/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.student.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.student.ui.internal.StudentActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StudentExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StudentActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StudentActivator.getInstance().getInjector(StudentActivator.ORG_XTEXT_EXAMPLE_STUDENT_STUDENT);
	}
	
}
