/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.student


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StudentStandaloneSetup extends StudentStandaloneSetupGenerated {

	def static void doSetup() {
		new StudentStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
