/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.student.scoping;

import org.xtext.example.student.scoping.AbstractStudentScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class StudentScopeProvider extends AbstractStudentScopeProvider {
}
