/**
 * generated by Xtext 2.11.0
 */
package org.wso2.vihanga.example.student.ui.contentassist;

import org.wso2.vihanga.example.student.ui.contentassist.AbstractStudentProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class StudentProposalProvider extends AbstractStudentProposalProvider {
}
