/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.student.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStudentScopeProvider extends DelegatingScopeProvider {
}
