/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.student.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.student.ui.AbstractStudentUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class StudentUiModule extends AbstractStudentUiModule {
  public StudentUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
