/*
 * generated by Xtext 2.11.0
 */
package org.wso2.vihanga.example.student.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class StudentUiModule extends AbstractStudentUiModule {
}
