/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.student;

import org.xtext.example.student.AbstractStudentRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StudentRuntimeModule extends AbstractStudentRuntimeModule {
}
